### ISSUE TITLE
Whether other parameters are supported, such as n=1024, q=12289, but the result is wrong

### ISSUE THREAD

**Issue by zzulb** [acmert/kyber-polmul-hw#1]
Hello, I modified the parameters as follows:
    n = 1024
    q = 12289
    w = 7
    wv = 8778
    nv= 12241 
The NTT and INTT results are correct, but the PWM results are wrong, I don't know what's the problem? How to modify the code?
Thanks!

**Comment by zzulb** [comment]
The problem has been solved, the parameters should be:
     n = 1024
     q = 12289
     w = 49
     wv = 1254
     nv= 12277

**Comment by acmert** [comment]
Hi, 
For those who might run into the same problem in the future, here's the mathematical explanation:

`w` should satisfy the condition: `1 = w^n mod q (i.e., 49**1024 % 12289 = 1)`.

Also, polynomial size in `HalfModPolMul()` function
https://github.com/acmert/kyber-polmul-hw/blob/d81714b508c201d80c8013f80caa12168c67e838/test_generator/test_generator.py#L237
was hardcoded for `N=256`. Line 241, 246 and 247 should be:

`Line 241 --> C_ntt = [0 for _ in range(N)]`
`Line 246 --> for i in range(N//2):`
`Line 247 --> w_pow = 2*intReverse(i,int(log(N//2,2)))+1`

I updated `test_generator.py` accordingly.
